### ISSUE TITLE
'super' object has no attribute 'queryset'

### ISSUE THREAD

**Issue by pritstift** [barseghyanartur/django-fobi#12]
i use the current fobi package 0.5.3. in the admin panel of django 1.8. I get the error

```
'super' object has no attribute 'queryset'
```

Howerer, i downgraded to django 1.7 in virtualenv and everything worked great again.

Any idea?

Find the traceback here https://gist.github.com/pritstift/434011e9b811fd52fdfe

**Comment by barseghyanartur** [comment]
@pritstift:

Thanks for reporting. Fixed in version 0.5.4.

**Comment by bhaugen** [comment]
I'm using 0.6.6 and still get that error.
http://dpaste.com/0QEN3M6

**Comment by barseghyanartur** [comment]
@bhaugen:

Thanks for reporting this. Fixed in version 0.6.7.

**Comment by bhaugen** [comment]
@barseghyanartur thanks for the quick response! We're new Fobi adopters, and quick bug fixes gives us confidence.
